#manage-order: 5000
version: '3.3'
volumes:
  libreoffice_exchange:

services:
  libreoffice:
    container_name: ${DCPREFIX}_libreoffice
    build: ../machines/libreoffice
    environment:
      INPUT: /tmp/lo/1
      OUTPUT: /tmp/lo/2
    volumes:
      - libreoffice_exchange:/tmp/lo
  odoo_base:
    volumes:
      - libreoffice_exchange:/opt/libreoffice
    environment:
      LIBREOFFICE_SEND: /opt/libreoffice/1
      LIBREOFFICE_RECEIVE: /opt/libreoffice/2
    depends_on:
        - libreoffice
