#manage-order: 5000
version: '3.3'
volumes:
  ${CUSTOMS}_cupsdatatoprint:

services:
  cups:
    container_name: ${PROJECT_NAME}_${CUSTOMS}_cups
    build: $ODOO_HOME/images/cups
    ports:
      - "${CUPS_PORT}:631"
    volumes:
      - ${HOST_RUN_DIR}/cups/to_print:/opt/toprint 
      - ${HOST_RUN_DIR}/cups/printed:/opt/printed 
      - ${HOST_RUN_DIR}/cups/printer_setup:/opt/printer_setup
    environment:
      WATCHPATH: /opt/toprint
      PRINTED_PATH: /opt/printed
      CONF_ROOT: /opt/printer_setup
  odoo_base:
    volumes:
      - ${CUSTOMS}_cupsdatatoprint:/opt/toprint 
    environment:
      CUPS_TOPRINT: /opt/toprint

