# manage-order 1000
services:
  odoo_base:
    build:
        context: $ODOO_HOME/images/odoo
        dockerfile: $ODOO_HOME/images/odoo/config/${ODOO_VERSION}/Dockerfile
        args:
          ODOO_VERSION: ${ODOO_VERSION}
          ODOO_PYTHON_VERSION: ${ODOO_PYTHON_VERSION}
          INSTALL_DOCKER_CLIENTS: ${INSTALL_DOCKER_CLIENTS}
          DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
    restart: unless-stopped
    volumes:
      - ${HOST_RUN_DIR}:/opt/run
      - ${HOST_RUN_DIR}/odoo_outdir:/opt/out_dir
      - ${DUMPS_PATH}:/opt/dumps
      - ${ODOO_FILES}:/opt/files
      - ${ODOO_HOME}/tools:/opt/tools
      - ${HOST_RUN_DIR}/debug:/tmp/debug
      - ${ODOO_HOME}/images/odoo/bin/update_modules.py:/update_modules.py
      - ${ODOO_HOME}/images/odoo/bin:/odoolib:ro
      - ${ODOO_HOME}/images/odoo/config/${ODOO_VERSION}/config:${ODOO_CONFIG_DIR}.template:ro
      - ${HOST_RUN_DIR}/intercom:/intercom
      - ~/.config/pudb:/home/odoo/.config/pudb
      - ${CUSTOMS_DIR}:/opt/src
      # copied by entrpoint to destination and correct UID/GID
      - ${ODOO_HOME}/images/odoo/odoo_modules/${ODOO_VERSION}:/tmp/odoo_server_tools.template
      - ${HOST_RUN_DIR}/odoo-shell-ipython:/home/odoo/.ipython
    environment:
      - OPENUPGRADE_TARGET_VERSION=${ODOO_VERSION}
      - ODOO_USER=odoo
      - ODOO_DATA_DIR=/opt/files
      - ODOO_HOME=/opt/odoo
      - ODOO_CONFIG_TEMPLATE_DIR=/etc/odoo/config.template
      - ODOO_SUDO_CMD=1
      - OUT_DIR=/opt/out_dir
      - RUN_DIR=/opt/run
      - INTERCOM_DIR=/intercom
      - SERVER_DIR=/opt/src/odoo
      - CUSTOMS_DIR=/opt/src
      - ODOOLIB=/odoolib
      - PYTHONPATH=/odoolib:/opt/tools
      - PATH=/odoolib:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - PYTHONBREAKPOINT=0
      - ODOO_SERVER_TOOLS_MODULES=/opt/odoo_server_tools
      - ODOO_FRAMEWORK_KEEP_SQL_CONNECTION=1
    command: /usr/bin/env python3 /odoolib/run.py
    entrypoint: ["/odoolib/entrypoint.py"]
    logging:
        options:
            max-size: 1g
