version: '3'
services:
  odoo:
    labels:
        odoo.web_container: '1'
        compose.merge: 'odoo_base'
    environment:
      IS_ODOO_WEBSERVER: 1
    environment:
      DEBUGGER_WATCH: /opt/src/.debug
      DEBUGGER_ODOO_PID: /tmp/odoo.debug.pid

  odoo_debug:
    restart: 'no'
    ports:
      - "0.0.0.0:${ODOO_PYTHON_DEBUG_PORT}:5678"
    labels:
        compose.merge: 'odoo_base'
    environment:
      ENDLESS_LOOP: 1
      DEBUGGER_WATCH: /opt/src/.debug
      DEBUGGER_ODOO_PID: /tmp/odoo.debug.pid

  odoo_cronjobs:
    labels:
        compose.merge: 'odoo_base'
        odoo.queuejob_container: '1'
    environment:
      IS_ODOO_CRONJOB: 1
    logging:
        options:
            max-size: 3g

  odoo_queuejobs:
    labels:
        compose.merge: 'odoo_base'
        odoo.queuejob_container: '1'
    environment:
      IS_ODOO_QUEUEJOB: 1
    logging:
        options:
            max-size: 3g

  odoo_update:
    labels:
        compose.merge: 'odoo_base'
    restart: 'no'
    command: echo 'good bye - it is ok!'
