#manage-order: 8000
services:
  proxy:
    labels:
        compose.merge: 'proxy_abstract'
    environment:
        ODOO_HOST: ${project_name}_odoo
        ROUNDCUBE_HOST: ${project_name}_roundcube
        THEIA_HOST: ${project_name}_theia_rewriter
        # WEBSSH_HOST: ${project_name}_webssh
