# manage-order 1000
services:
  robot:
    build:
        context: $ODOO_HOME/images/robot
    environment:
        OUTPUT_DIR: /opt/output
    volumes:
        - ${CUSTOMS_DIR}/robot_output:/opt/output
        - ${ODOO_HOME}/images/robot/robotest.py:/opt/robot/robotest.py
        - ${ODOO_HOME}/images/robot/robotest.sh:/opt/robot/robotest.sh
        - ${ODOO_HOME}/images/robot/keywords:/opt/robot/keywords
        - ${ODOO_HOME}/images/robot/library:/opt/robot/library
